name: Masscan and ShuffleDNS Installation

on: [push]

jobs:
  install-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Masscan
      run: |
        git clone https://github.com/blechschmidt/massdns.git
        cd massdns
        make
#        masscan --version

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Install ShuffleDNS
      run: |
        go install -v github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest
        shuffledns -version

#    - name: Verify installations
#      run: |
#        masscan --version
#        shuffledns -version

    - name: executing DNS Brute
      run: |
        cd ../
        pwd
        cd bio_electronic_static_adit
        ls
        sudo apt-get install -y crunch
        crunch 1 4 abcdefghijklmnopqrstuvwxyz1234567890 > 4_chars.txt
        wget https://github.com/zzzteph/substats/raw/main/wordlists/all
        curl -s https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt -o best-dns-wordlist.txt
        curl -s https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt -o 2m-subdomains.txt
        curl -s https://wordlists-cdn.assetnote.io/data/automated/httparchive_subdomains_2024_01_28.txt -o all_subs.txt
        cat best-dns-wordlist.txt 2m-subdomains.txt 4_chars.txt all_subs.txt all | sort -u > subdomains-assetnote-merged.txt
        cat subdomains-assetnote-merged.txt | wc -l
        mkdir outputfiles
        shuffledns -w subdomains-assetnote-merged.txt -d goparrot.ai -r .resolvers -m massdns/bin/massdns -o output.txt
        cat output.txt | while read line;do shuffledns -w subdomains-assetnote-merged.txt -d $line -r .resolvers -m massdns/bin/massdns -o $line_output.txt -silent;cp $line_output.txt outputfiles;done

    - name: Install zip
      run: sudo apt-get install zip

    - name: Zip the folder
      run: zip -r outputfiles.zip outputfiles/
      
    - name: Upload output as artifact
      uses: actions/upload-artifact@v2
      with:
        name: command-output
        path: outputfiles.zip
